networks:
  reverse_proxy_network:
    driver: bridge
    name: reverse_proxy_network
    external: true

services:
  web:
    image: nginx
    container_name: server_fingerprint_ngnix
    volumes:
    - ./templates:/etc/nginx/templates
    - ./html:/usr/share/nginx/html
    ports:
    - "8030:80"
    environment:
    - NGINX_HOST=nihilia.xyz
    - NGINX_PORT=80
    restart: always
    networks:
      - reverse_proxy_network